/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppLearnRouteImport } from './routes/_app/learn'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppTeacherIndexRouteImport } from './routes/_app/teacher.index'
import { Route as AppTeacherStudentIdRouteImport } from './routes/_app/teacher.$studentId'
import { Route as AppLessonLessonIdRouteImport } from './routes/_app/lesson.$lessonId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherIndexRoute = AppTeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherStudentIdRoute = AppTeacherStudentIdRouteImport.update({
  id: '/teacher/$studentId',
  path: '/teacher/$studentId',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonLessonIdRoute = AppLessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/learn': typeof AppLearnRoute
  '/onboarding': typeof AppOnboardingRoute
  '/progress': typeof AppProgressRoute
  '/lesson/$lessonId': typeof AppLessonLessonIdRoute
  '/teacher/$studentId': typeof AppTeacherStudentIdRoute
  '/teacher/': typeof AppTeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/learn': typeof AppLearnRoute
  '/onboarding': typeof AppOnboardingRoute
  '/progress': typeof AppProgressRoute
  '/lesson/$lessonId': typeof AppLessonLessonIdRoute
  '/teacher/$studentId': typeof AppTeacherStudentIdRoute
  '/teacher': typeof AppTeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/learn': typeof AppLearnRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/lesson/$lessonId': typeof AppLessonLessonIdRoute
  '/_app/teacher/$studentId': typeof AppTeacherStudentIdRoute
  '/_app/teacher/': typeof AppTeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/learn'
    | '/onboarding'
    | '/progress'
    | '/lesson/$lessonId'
    | '/teacher/$studentId'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/learn'
    | '/onboarding'
    | '/progress'
    | '/lesson/$lessonId'
    | '/teacher/$studentId'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/learn'
    | '/_app/onboarding'
    | '/_app/progress'
    | '/_app/lesson/$lessonId'
    | '/_app/teacher/$studentId'
    | '/_app/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher/': {
      id: '/_app/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AppTeacherIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher/$studentId': {
      id: '/_app/teacher/$studentId'
      path: '/teacher/$studentId'
      fullPath: '/teacher/$studentId'
      preLoaderRoute: typeof AppTeacherStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lesson/$lessonId': {
      id: '/_app/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof AppLessonLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppLearnRoute: typeof AppLearnRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProgressRoute: typeof AppProgressRoute
  AppLessonLessonIdRoute: typeof AppLessonLessonIdRoute
  AppTeacherStudentIdRoute: typeof AppTeacherStudentIdRoute
  AppTeacherIndexRoute: typeof AppTeacherIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppLearnRoute: AppLearnRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProgressRoute: AppProgressRoute,
  AppLessonLessonIdRoute: AppLessonLessonIdRoute,
  AppTeacherStudentIdRoute: AppTeacherStudentIdRoute,
  AppTeacherIndexRoute: AppTeacherIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
